import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <head>
        <title>Jerome's Portfolio</title>
      </head>
      <head>
        <meta name="description" content="generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900 dark:text-white">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">Developed By Jerome</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className=" text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Jerome Blaek
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl">
              Developer and designer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-600 md:text-xl max-w-xl mx-auto dark:text-white-300">
              As a skilled freelance web developer and design content creator, I
              possess a unique combination of technical expertise{" "}
              <p>
                and creativity that enables me to create engaging and visually
                stunning online experiences.{" "}
                <strong>Let's get to creating.</strong>
              </p>
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={deved} layout="fill" objectFit="cover" alt="deved" />
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1">About </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I am a skilled <span className="text-teal-500">Developer</span>{" "}
              and <span className="text-teal-500">content designer</span> with
              years of experience creating engaging and effective online
              experiences. With a strong focus on both technical expertise and
              creativity, I am committed to delivering exceptional results for
              my clients.
            </p>
            <h3 className="text-3xl py-1">Services l offer </h3>
            <li>
              <span className="text-teal-500">Web Development</span>: I
              specialize in developing custom websites using a variety of
              programming languages and content management systems, including
              HTML, CSS, JavaScript, PHP, WordPress, React and Next Js.
            </li>
            <li>
              <span className="text-teal-500">Software Development</span>: I
              have experience developing custom software applications for
              businesses, including mobile applications, desktop applications,
              and web-based applications.
            </li>
            <li>
              <span className="text-teal-500">Graphic Design</span>: I have a
              strong background in graphic design, enabling me to create
              visually stunning graphics and layouts for websites, social media
              platforms, and other digital assets.
            </li>
            <li>
              <span className="text-teal-500">Content Creation</span>: I
              specialize in creating engaging and informative content for
              websites, social media platforms, and other digital channels,
              including blog posts, articles, videos, and infographics.
            </li>
          </div>
          <div className="lg:flex gap-10 justify-items-center">
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={code} width={100} height={100} alt="code" />
              <h3 className="text-lg font-medium pt-8 pb-2">
                software dev
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">developing tools</h4>
              <p className="text-gray-600 py-1">Integrated Development Environments (IDEs)</p>
              <p className="text-gray-600 py-1">Text Editors (VS Code)</p>
              <p className="text-gray-600 py-1">Package Managers</p>
              <p className="text-gray-600 py-1">Code Linters</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={consulting} width={100} height={100} alt="consulting" />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Consulting DevOps
              </h3>
              <p className="py-2">
                Providing expert advice, guidance, and support to clients who are
                seeking to solve complex technological challenges or improve
                their software development processes.
              </p>
              <h4 className="py-4 text-teal-600">Tools l use</h4>
              <p className="text-gray-600 py-1">Cloud Platforms</p>
              <p className="text-gray-600 py-1">Monitoring and Logging</p>
              <p className="text-gray-600 py-1">Containerization</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={design} width={100} height={100} alt="design" />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design tools l use</h4>
              <p className="text-gray-600 py-1">Photoshop</p>
              <p className="text-gray-600 py-1">Illustrator</p>
              <p className="text-gray-600 py-1">Figma</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1">Portfolio</h3>
            <h2 className="text-lg py-1">1.Medicini</h2>
            <li>
              Developed a custom website using HTML, CSS, and JavaScript for a
              small business in the healthcare industry.
            </li>
            <li>
              Created engaging content, including blog posts and videos, to
              promote the business and drive traffic to the website.
            </li>
            <li>
              Designed visually appealing graphics and layouts for the website
              and social media platforms.
            </li>
            <h2 className="text-lg py-1">2.Orbitvase Fintech</h2>
            <li>
              Developed a custom mobile application for a startup company in the
              finance industry using React Native.
            </li>
            <li>
              Designed the user interface and experience, incorporating user
              feedback to optimize the design.
            </li>
            <li>
              Created informative content, including articles and infographics,
              to educate users on the features and benefits of the application.
            </li>
            <h2 className="text-lg py-1">3.Ark-Market</h2>
            <li>
              Developed a custom e-commerce website using WordPress and
              WooCommerce for a small business in the retail industry.
            </li>
            <li>
              Designed the website layout and graphics to showcase the products
              and make it easy for customers to make purchases.
            </li>
            <li>
              Created engaging product descriptions and optimized the website
              for search engines to drive traffic and increase sales.
            </li>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                src={web1}
                alt="web1"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web2}
                alt="web2"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web3}
                alt="web3"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web4}
                alt="web4"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web5}
                alt="web5"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web6}
                alt="web6"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
